version: "3"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: vardast@1234
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - myNet
    deploy:
      resources:
        limits:
          cpus: '3'  # 0.5 * 3
          memory: 3G 

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - myNet
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=g90pM89O  
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 2G

  storage:
    image: minio/minio
    ports:
      - 81:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: farbod
      MINIO_ROOT_PASSWORD: g90pM89O
    volumes:
      - ./storage:/data
    command: server /data --console-address ":9090"
    networks:
      - myNet
    deploy:
      resources:
       limits:
         cpus: '6'  # Adjust based on available cores
         memory: 6G 
  web:
    build: .
    restart: always
    ports:
      - "3080-3087:3080"
    volumes:
      - .:/app
    networks:
      - myNet
    deploy:
      resources:
        limits:
          cpus: '10'  # Set the CPU limit to 10 cores
          memory: 3G
    # depends_on:
    #   - elasticsearch
    #   - logstash_image
    #   - kibana

  # elasticsearch:
  #   image: elasticsearch:7.16.2
  #   container_name: elasticsearch
  #   restart: always
  #   volumes:
  #     - elastic_data:/usr/share/elasticsearch/data/
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTIC_PASSWORD=farbod
  #     - xpack.security.enabled=true
  #     - xpack.security.authc.api_key.enabled=true
  #     - server.publicBaseUrl=https://search.vardast.com
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   networks:
  #     - myNet
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '3.0'
  #         memory: 6G  # 2G * 3

  # logstash_image:
  #   image: logstash:7.16.2
  #   volumes:
  #     - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf
  #   restart: always
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '9600:9600'
  #   environment:
  #     - LS_JAVA_OPTS=-Xmx256m -Xms256m
  #   networks:
  #     - myNet
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '3'
  # kibana:
  #   image: kibana:7.16.2
  #   container_name: kibana
  #   ports:
  #     - '5602:5601'
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_URL=https://search.vardast.com
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD=farbod
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - myNet
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.5'
  #         memory: 1536M

volumes:
  pg_data:
  # elastic_data: {}

networks:
  myNet:
    external: true